### ISSUE TITLE
Tourney ID

### ISSUE THREAD

**Issue by Lasp10** [benjmor/tabroom_auto_summarize#33]
How do I get the tournament IDs for tournaments?

**Comment by benjmor** [comment]
The URL of the main page of the tournament on Tabroom.com will contain the tournament ID.

![image](https://github.com/benjmor/tabroom_auto_summarize/assets/44407400/c0df93b4-a39c-4fcd-8205-7245e59cddfc)

The main website page also now displays tournaments that already have results.
